// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycoqcyzyippbqsmudhlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljb3FjeXp5aXBwYnFzbXVkaGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTg1NDksImV4cCI6MjA2NjQ3NDU0OX0.CL3MwCOj-CLub2RJMFA6Ov1Mh1DAfKswvbBRUGMChFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);